services:
  distribution:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OCI_REGISTRY_PORT: ${OCI_REGISTRY_PORT}
        OCI_REGISTRY_ROOTDIR: ${OCI_REGISTRY_ROOTDIR}
    restart: unless-stopped
    ports:
      - "${OCI_REGISTRY_PORT}:8968"
    volumes:
      - registry_data:${OCI_REGISTRY_ROOTDIR}
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

      OCI_REGISTRY_URL: ${OCI_REGISTRY_URL}
      OCI_REGISTRY_PORT: ${OCI_REGISTRY_PORT}
      OCI_REGISTRY_STORAGE: ${OCI_REGISTRY_STORAGE}
      OCI_REGISTRY_ROOTDIR: ${OCI_REGISTRY_ROOTDIR}
      OCI_REGISTRY_PUBLIC_URL: ${OCI_REGISTRY_PUBLIC_URL}

      PASSWORD_SALT: ${PASSWORD_SALT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_LIFETIME_SECONDS: ${JWT_LIFETIME_SECONDS}
      RUST_LOG: ${RUST_LOG}
    depends_on:
      - db

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  db_data:
  registry_data:
