[package]
name = "libscheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bitflags = "2.9.2"
etcd-client = "0.16.1"
log = "0.4.27"
serde = "1.0.219"
serde_yaml = "0.9.34"
tokio = "1.46.1"
uuid = "1.17.0"
