repos:
-   repo: local
    hooks:
    -   id: rust-linting
        name: Rust linting
        description: Run cargo fmt on files included in the commit.
        entry: cargo fmt --manifest-path project/Cargo.toml --all --
        pass_filenames: false
        types: [file, rust]
        language: system
    -   id: rust-clippy-fix
        name: Rust clippy fix
        description: Run cargo clippy fix on files included in the commit.
        entry: cargo clippy --manifest-path project/Cargo.toml --workspace --fix
        pass_filenames: false
        types: [file, rust]
        language: system