name: 'Install System Tools and Dependencies'

runs:
  using: "composite"
  steps:
    - name: Setup Rust Toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: clippy rustfmt
        cache-workspaces: |
          ./project
        cache-directories: |
          ./project/target

    - name: Update APT Cache
      run: sudo apt-get update
      shell: bash

    - name: Install System Tools
      run: sudo apt-get install -y build-essential clang lld pkg-config zstd curl
      shell: bash

    - name: Install System Libraries
      run: sudo apt-get install seccomp libseccomp-dev
      shell: bash

    - name: Restore cache
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          /home/runner/.cargo/bin/buck2
        key: buck2-binary
