[workspace]
members = [
    "distribution",
    "libcgroups", 
    "libcni",
    "libcontainer", "rkb",
    "rkl"
]

default-members = ["distribution", "rkl"]
resolver = "1"

[workspace.dependencies]
distribution = { path = "distribution" }
libcgroups = { path = "libcgroups" }
libcni = { path = "libcni" }
libcontainer = { path = "libcontainer" }
