on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: ["stable", "beta", "nightly"]

    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install ${{ matrix.rust-version }}
      - run: cargo +${{ matrix.rust-version }} test --all

  msrv-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install 1.61
      - run: cargo +1.61 check --all

  ui-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: RUSTFLAGS='--cfg run_ui_tests' cargo +stable test ui

  test-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --check --all
