cargo_env = true
env = { "CARGO_MANIFEST_LINKS" = "ring_core_0_17_14_", "RING_CORE_PREFIX" = "ring_core_0_17_14_", CARGO_PKG_VERSION_PRE = "" }
extra_srcs = ["src/data/alg-rsa-encryption.der", "src/ec/**/*.der"]

[buildscript.run]
env = { CARGO_MANIFEST_LINKS = "ring_core_0_17_14_", OPT_LEVEL = "3", CARGO_PKG_VERSION_MAJOR = "0", CARGO_PKG_VERSION_MINOR = "17", CARGO_PKG_VERSION_PATCH = "14", CARGO_PKG_VERSION_PRE = "" }
