[workspace]

[package]
# Pseudo-package whose dependencies are imported and buckified
name = "rust-third-party"
version = "0.0.0"
edition = "2021"
publish = false

# Dummy target to keep Cargo happy
[[bin]]
name = "top"
path = "top/main.rs"

# List of packages to be imported, with version constraints, features
# and all options Cargo supports.
[dependencies]
anyhow = "1.0.98"
async-fs = { version = "2.1.1"}
async-std = "1.12"
async-trait = "0.1.86"
async-global-executor = { version = "2.4.1" }
async-lock = { version = "3.3.0" }
async-notify = "0.3"
async-io = { version = "2.3.1" }
async-process = { version = "2.1.0" }
axum = "0.8.1"
aws-lc-sys = "0.29.0"
bitflags = "2.9.0"
bincode = "1.3.3"
bytes = "1.10.1"
caps = "0.5.5"
chrono = { version = "0.4", default-features = false, features = [
    "clock",
    "serde",
] }
clap = { version = "4.5.32", features = ["derive"] }
cni-plugin = { version = "0.2.1", features = ["with-smol"] }
context = "3.0.0"
dockerfile-parser = "0.9.0"
dotenvy = "0.15.0"
env_logger = "0.11.7"
errno = { version = "0.3.10", optional = true }
etcd-client = "0.15.0"
fastrand = "^2.3.0"
fixedbitset = "0.5.7"
flate2 = "1.1.1"
futures = "0.3.31"
futures-channel = { version = "0.3.30", features = ["sink"] }
futures-util = "0.3.31"
hex = "0.4.3"
http-body = "0.4.5"
hyper = "0.14.27"
idna_adapter = "=1.2.0"
ipnetwork = "0.17.0"
lazy_static = "1.5.0"
libbpf-sys = { version = "1.5.0", optional = true }
libc = "0.2.171"
liboci-cli = "0.5.1"
libseccomp = "0.3.0"
log = "0.4.26"
macaddr = "1.0.1"
native-tls = "0.2.14"
nc = "0.9.5"
netlink-packet-route = "0.22.0"
nix = { version = "0.29.0", features = [
    "signal",
    "user",
    "fs",
    "socket",
    "sched",
    "mount",
    "mman",
    "resource",
    "dir",
    "term",
    "hostname",
    "process",
] }
num-bigint = "0.4.6"
num-traits = "0.2.19"
oci-spec = { version = "~0.7.1", features = ["runtime"] }
once_cell = "1.21.2"
openssl = { version = "0.10.71", features = ["vendored"] }
prctl = "1.0.0"
procfs = "0.17.0"
prost = "0.13.5"
prost-types = "0.12.6"
protobuf = "=3.2.0"
quinn = "0.11.8"
radix_trie = "0.2.1"
rand = "0.9.0"
rbpf = { version = "0.3.0", optional = true }
regex = { version = "1.10.6", default-features = false, features = [
    "std",
    "unicode-perl",
] }
reqwest = { version = "0.12.7", features = ["json", "blocking"] }
rcgen = "0.12.1"
rfuse3 = { version = "0.0.3", features = ["tokio-runtime", "unprivileged"] }
rtnetlink =  "0.16.0"
rust-criu = "0.4.0"
rust-cni = "0.1.2"
rustls = "0.23" 
safe-path = "0.1.0"
semver = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.138"
serde_yaml = "0.9"
sha2 = "0.10.8"
sha256 = "1.6.0"
slab = "0.4.9"
tar = "0.4.44"
tempfile = "3.19.1"
thiserror = "2.0.12"
tokio = { version = "1.44.0", features = ["full"] }
tokio-util = { version = "0.7.13", features = ["io"] }
tonic = "0.13"
tracing = { version = "0.1.41", features = ["attributes"] }
tracing-journald = "0.3.1"
tracing-subscriber = { version = "0.3.19", features = ["json", "env-filter"] }
trait-make = "0.1"
uuid = { version = "1.15.1", features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
] }
vm-memory = "0.16.1"
vmm-sys-util = "0.12.1"
walkdir = "2.3"
daemonize = "0.5.0"
which = { version = "4.4.2" }
tabwriter = "1.4.1"
lru = "0.16.0"


# Local patches - typically git references
[patch.crates-io]
